"""add merchant logo_url

Revision ID: 993cd5b3df93
Revises: 8bd125f848fd
Create Date: 2025-12-19 14:57:45.364233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '993cd5b3df93'
down_revision: Union[str, Sequence[str], None] = '8bd125f848fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('logo_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'logo_url')
    # ### end Alembic commands ###
